/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCatchSplatRouteImport } from './routes/api/public/catch.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCatchSplatRoute = ApiPublicCatchSplatRouteImport.update({
  id: '/api/public/catch/$',
  path: '/api/public/catch/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/catch/$': typeof ApiPublicCatchSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/catch/$': typeof ApiPublicCatchSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/catch/$': typeof ApiPublicCatchSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/catch/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/catch/$'
  id: '__root__' | '/' | '/api/public/catch/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCatchSplatRoute: typeof ApiPublicCatchSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catch/$': {
      id: '/api/public/catch/$'
      path: '/api/public/catch/$'
      fullPath: '/api/public/catch/$'
      preLoaderRoute: typeof ApiPublicCatchSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCatchSplatRoute: ApiPublicCatchSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
